# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    name: list on nuget
    runs-on: windows-latest
    env:
      Project_Path: src/LifxCloud.NET/LifxCloud.NET/LifxCloud.NET.csproj
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
     
      # Use Nerdbank.GitVersioning to set version variables: https://github.com/AArnott/nbgv
      - name: Use Nerdbank.GitVersioning to set version variables
        uses: dotnet/nbgv@v0.3
        with:
          setAllVars: true

      # Required for a specific dotnet version that doesn't come with ubuntu-latest / windows-latest
      # Visit bit.ly/2synnZl to see the list of SDKs that are pre-installed with ubuntu-latest / windows-latest
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100

      # Update the version before build
      - name: Update manifest version
        run: |
          [xml]$manifest = get-content ".\$env:Project_Path"
          $manifest.Project.PropertyGroup.Version = "$env:NBGV_SimpleVersion.0"
          $manifest.save(".\$env:Project_Path")

      # Publish
      - name: publish on version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: "src/LifxCloud.NET/LifxCloud.NET/LifxCloud.NET.csproj" # Relative to repository root
          # VERSION_FILE_PATH: Directory.Build.props # Filepath with version info, relative to repository root. Defaults to project file
          # VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
          VERSION_STATIC: true # Bypasses version resolution; useful for external providers like Nerdbank.GitVersioning
          # TAG_COMMIT: true # Flag to enable / disalge git tagging
          # TAG_FORMAT: v* # Format of the git tag, [*] gets replaced with version
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key
          PACKAGE_NAME: LifxCloud


